### ISSUE TITLE
Gallery page: There is no parent and root page in the breadcrumbs of the gallery inside extended & compact album's.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Network-Packaging#49]
It happens for newly added album's.

![2016-02-09_1601-brdcrm](https://cloud.githubusercontent.com/assets/13309730/12913887/4626e6b8-cf47-11e5-8610-6bb9ac7524ae.png)

**Comment by Santosh-titan** [comment]
Its happen some times because of Nextgen gallery issues.
