### ISSUE TITLE
News page: Inconsistent news featured image size

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Network-Packaging#78]
![untitled-1-news](https://cloud.githubusercontent.com/assets/13309730/13102496/05f56df6-d575-11e5-8a67-e08136175dd5.png)

**Comment by kabirkhan123** [comment]
Given design is not followed by bootstrap design standards.Please confirm with your PM.

**Comment by Santosh-titan** [comment]
Given design is not followed by bootstrap design standards.Please confirm with your PM.

**Comment by roseliesromeo** [comment]
Design error
