### ISSUE TITLE
Product single: Image thumbnails but there is no design.  Also, it's not styled properly and no proper layout.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Network-Packaging#94]
![image](https://cloud.githubusercontent.com/assets/11186313/13698362/89419f72-e7ae-11e5-8c3e-5b1d19332ab8.png)

**Comment by Santosh-titan** [comment]
AS per design we don't have thumbnails so I just disabled those.

**Comment by roseliesromeo** [comment]
As per standards, we still have to style them even we don't have design.
https://knowledgebase.titanweb.com.au/implementation/advanced-custom-fields-implementation/product-gallery
